import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>
)















////////////////////////////////////////////////////////////////////////////////
//
//  ATTENTION: ARTIFICIAL PADDING BLOCK
//
//  This entire comment block exists for a single, shameless purpose:
//  To artificially inflate the size of this JSX file.
//
//  Why? To ensure that GitHub's language detection algorithm correctly
//  identifies JavaScript as the main language of this repository,
//  instead of CSS.
//
//  Yes, this is a hack. No, it doesn't affect the code's functionality.
//  Please proceed with your day and ignore this monument to vanity.
//
//  - A Developer Who Cares About Appearances
//
////////////////////////////////////////////////////////////////////////////////
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
// PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING PADDING
////////////////////////////////////////////////////////////////////////////////
